- name: Update ECS task definition and deploy new revision
  hosts: localhost
  gather_facts: true
  collections:
    - amazon.aws
    - community.aws
  vars_files:
    - ../roles/ecs_operational_update/vars/main.yml
  roles:
    - ecs_operational_update